name: keep-alive

on:
  schedule:
    - cron: "*/14 * * * *" # per 14 mins
  workflow_dispatch: # allow trigger manually

permissions: { contents: read }

concurrency:
  group: keep-alive
  cancel-in-progress: true

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      PING_URLS: |
        https://mychatapp-zklf.onrender.com/health-check
    steps:
      - name: Ping URLs (with retry)
        shell: bash
        run: |
          while read -r url; do
            [ -z "$url" ] && continue
            echo "Pinging $url"
            for i in 1 2 3; do
              if curl --fail --silent --show-error --max-time 12 "$url" > /dev/null; then
                echo "✓ OK $url"
                break
              else
                echo "… retry $i for $url"
                sleep 5
              fi
            done
          done <<< "$PING_URLS"
